server:
  context-path: /
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: SAT Support Web Application
  messages:
    basename: messages/messages
    encoding: UTF-8
  jpa:
    database: postgresql
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          batch_versioned_data: true
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_database
    username: test_user
    password: qwerty
    hikari:
      maximum-pool-size: 15
logging:
  path: ./log

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/oauth/user
      prefer-token-info: false
      filter-order: 3
  basic:
    enabled: false

